# -*- coding: utf-8 -*-
"""nsfw-detector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOtoPdJnmetqskV8YhZrMSfxlWx-HWkS
"""

import numpy as np
import matplotlib.pyplot as plt
import pickle
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import EarlyStopping
import time
import pandas as pd
from keras.optimizers import SGD


#loads stored X data for usage
pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

#loads stored y data
pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

#trains the model through 6 layers - optimized do not change
model = Sequential()

model.add(Conv2D(32, (3, 3), input_shape=X.shape[1:], padding= 'same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten()) 

model.add(Dropout(0.4))
model.add(Dense(32))
model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('sigmoid'))

opt = SGD(learning_rate=0.001)
model.compile(loss='binary_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])

#converts data to array to bypass error - do not touch
X = np.array(X)
y = np.array(y)

#model is fitted with optimized variables
model_history = model.fit(X, y, batch_size=32, epochs=10, validation_split=0.3)

#model is saved for further usage
model.save('6xn-CNN.model')

#model shows all data for developer analysis
print(model.summary()) 
pd.DataFrame(model_history.history).plot(figsize=(8,5))
plt.show()

import cv2

def prepare():
  img_array = cv2.imread('download10.jpg')
  new_array = cv2.resize(img_array, (80, 80))
  ary = new_array.reshape(-1, 80, 80, 3)
  return ary

prediction = model.predict(prepare())

if(prediction < 0.5):
  print('NSFW')
elif(prediction > 0.5):
  print('Normal')